# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/Visualize-Understand-CNNs',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/Visualize-Understand-CNNs',
                'lib_path': 'nbs/lib'},
  'syms': {}}
